City page
Melichka/TravelPlan pull request #3
Opened 2024-01-10 05:46 UTC by Melichka

![image](https://github.com/Melichka/TravelPlan/assets/83559007/1a83383a-4439-44cd-85ed-8a2c43980e33)

2024-01-10 21:48 UTC, the-homeless-god requested changes

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/public/assets/images/bubbleforcitypage.svg
We need not to provide the usage scope for the image
It would be better just to follow for common names
Like `bubble-background.svg`

Or you can create subfolders in images folder for pages

Like `city-page/background.svg`

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/App.tsx
> +import "./index.css";
Styles should be groupped at the bottom of imports

Please connect ESLint & Prettier plugin for automatically groupping of imports by formatter

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/App.tsx
>          </div>
Do we really need this div here?

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/EntertainmentButton/EntertainmentButton.tsx
> +import "./styles.css";
Same

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/EntertainmentButton/EntertainmentButton.tsx
> +import { MenuButton } from "../MenuButton/MenuButton";
Let's configure project to follow for imports like `src/components/` instead of `../../components/`

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/EntertainmentButton/constants.ts
> +export const ENTERTAINMENT = "Развлечения";
Let's setup `i18n` for translations

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/EntertainmentButton/styles.css
> +}
Let's get rid of `-style` postfix everywhere

```suggestion
.text-button {
  font-family: "Roboto";
  font-size: 24px;
  color: #A61700;
}

.button {
  background-color: #FFBA73;
}
```

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/HeaderTitle/styles.css
> +}
Let's setup SCSS

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/SearchBar/SearchBar.tsx
> +            borderColor: "#A61700", // Также установка цвета рамки для активного состояния
I would save them. But I would like to move the content of sx to the separated function and store comments at that function

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/SearchBar/styles.css
> +}
Add empty line after this line

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/components/SearchBar/styles.css
> +
Drop this line

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/index.css
> +}
Combine together

```suggestion
h2, h3 {
  display: flex;
  font-family: 'Righteous';
  font-style: normal;
  margin-block-start: 0;
  margin-block-end: 0;
}

h2 {
  font-size: 32px;
}

h3 {
  font-size: 24px;
}
```

2024-01-10 21:48 UTC, the-homeless-god commented on frontend/src/pages/CityPage/styles.css
> +  height: 100vh;
https://www.youtube.com/watch?v=utcDm7QuyPw

2024-01-11 05:44 UTC, Melichka commented on frontend/src/components/SearchBar/SearchBar.tsx
> +            borderColor: "#A61700", // Также установка цвета рамки для активного состояния
Can I save this content of sx if I need only 1 line of code?
Like this
``sx={{
          "& .MuiOutlinedInput-root": {
            borderRadius: 50,
          },
        }}``

2024-01-11 21:08 UTC, the-homeless-god requested changes

2024-01-11 21:08 UTC, the-homeless-god commented on frontend/src/components/HeaderTitle/styles.css.map
> +{"version":3,"sourceRoot":"","sources":["styles.scss"],"names":[],"mappings":"AAGA;EACE;EACA;EACA;EACA;;AAEA;EACE,OAVU;;AAaZ;EACE;EACA,OAdW","file":"styles.css"}
Need to add .css.map файлы into .gitignore on repo level

2024-01-11 21:08 UTC, the-homeless-god commented on frontend/src/components/MenuButton/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Righteous&family=Roboto&display=swap");
Get rid of it

2024-01-11 21:08 UTC, the-homeless-god commented on frontend/src/components/SearchBar/styles.scss
> +$big-border-radius: 50px;
Ideally, you can define variables.scss and import it everywhere needed, contact with @Uzhastin-Nikita to resolve it

2024-01-11 21:08 UTC, the-homeless-god commented on frontend/src/pages/CityPage/index.ts
Please avoid usage of PascalCase at folders name

2024-01-11 21:08 UTC, the-homeless-god commented on frontend/src/pages/CityPage/styles.scss
> +.city-page-main-cadr-image {
A typo `cadr`

2024-01-11 21:08 UTC, the-homeless-god commented on frontend/src/pages/CityPage/styles.scss
> +  height: 70dvh;
https://sass-scss.ru/documentation/rasshirenie_css/ssilka_na_roditelya_selektora/

https://sass-scss.ru/documentation/rasshirenie_css/vlozhennie_pravila/

2024-01-12 09:05 UTC, the-homeless-god requested changes

2024-01-12 09:05 UTC, the-homeless-god commented on frontend/src/pages/SearchPage/images/background.svg
We need not to provide the usage scope for the image
It would be better just to follow for common names
Like bubble-background.svg

Or you can create subfolders in images folder for pages

Like public/assets/pages/city/background.svg

2024-01-15 12:46 UTC, Uzhastin-Nikita commented on frontend/src/components/InputField/styles.scss
> +  background-color: #FFBA73;
Let`s  use mixins from scss variables

2024-01-15 12:46 UTC, Uzhastin-Nikita commented on frontend/src/components/MenuButton/styles.module.scss
> +}
Formate document please

2024-01-15 12:46 UTC, Uzhastin-Nikita commented on frontend/src/components/SubmitButton/SubmitButton.tsx
> +    <div className="submit-button">
Let's use `styles.module.scss` for 11 string

2024-01-15 12:46 UTC, Uzhastin-Nikita commented on frontend/src/components/SubmitButton/styles.scss
> +  background-color: #FFA040;
Could you use mixins from `scss`, please?

2024-01-15 12:46 UTC, Uzhastin-Nikita commented on frontend/src/components/SupportButton/SupportButton.tsx
> +};
Could you use styles module for 12 string?

2024-01-15 12:46 UTC, Uzhastin-Nikita commented on frontend/src/components/SupportButton/styles.scss
> +}
Could you refactor this file?

`@use` => `@import`

```suggestion
@use "../styles/variables/color.scss";
@use "../styles/variables/font.scss";

.text-button-style {
  font-family: $font-stack;
  font-size: 24px;
  color: $text-color;
}
```

2024-01-15 13:24 UTC, Uzhastin-Nikita approved these changes

2024-01-15 15:51 UTC, the-homeless-god approved these changes
LGTM 🚀

2024-01-16 13:38 UTC, merged